name: Restrict Branch Push

on: push

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/YamaguchiYujin-patch-1" ]]; then
            echo "Push to this branch is not allowed!"
            exit 1
          fi
